#!/usr/bin/env tsx
/**
 * Database migration tool for the seller server (SQLite / better-sqlite3).
 *
 * Usage:
 *   npm run db:migrate          — apply schema to registry DB (safe, idempotent)
 *   npm run db:reset            — DROP the registry DB file and recreate from scratch
 *
 * The registry DB (_data/catalog.db) holds: users, settings, stores.
 * Per-store DBs (_data/stores/{slug}.db) are created automatically on first
 * access — no separate migration step needed for them.
 */
import 'dotenv/config'; // ← must be first — loads .env before DATA_DIR is evaluated
import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { initRegistrySchema, initStoreSchema } from './schema.js';
import { DATA_DIR } from './client.js';
import bcrypt from 'bcryptjs';

// ── .env auto-setup ───────────────────────────────────────────────────────────
// Non-technical sellers shouldn't need to touch the .env file.
// If it's missing or has insecure placeholder values we fix it automatically.
const __dir = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.resolve(__dir, '../../../.env');          // prompt-commerce/.env
const EXAMPLE_PATH = path.resolve(__dir, '../../../.env.example');

const KNOWN_WEAK_SECRETS = new Set([
  'change-me-to-a-long-random-string',
  'change-me-in-production',
  'replace_with_generated_secret',
  '',
]);

const KNOWN_WEAK_PASSWORDS = new Set([
  'admin123',
  'password',
  '123456',
  '',
]);

function ensureEnvFile(): void {
  // Create .env from .env.example if it doesn't exist yet
  if (!fs.existsSync(ENV_PATH)) {
    const template = fs.existsSync(EXAMPLE_PATH)
      ? fs.readFileSync(EXAMPLE_PATH, 'utf8')
      : '# Auto-generated by Prompt Commerce\n';
    fs.writeFileSync(ENV_PATH, template, 'utf8');
    console.log('✔  Created .env from .env.example');
  }
}

function patchEnvValue(key: string, value: string): void {
  ensureEnvFile();
  let content = fs.readFileSync(ENV_PATH, 'utf8');
  const lineRe = new RegExp(`^(#\\s*)?${key}=.*$`, 'm');
  const newLine = `${key}=${value}`;
  if (lineRe.test(content)) {
    content = content.replace(lineRe, newLine);
  } else {
    content += `\n${newLine}\n`;
  }
  fs.writeFileSync(ENV_PATH, content, 'utf8');
}

// ── Ensure JWT_SECRET is set and strong ───────────────────────────────────────
const currentSecret = process.env.JWT_SECRET ?? '';
if (!currentSecret || currentSecret.length < 32 || KNOWN_WEAK_SECRETS.has(currentSecret.toLowerCase())) {
  const generated = crypto.randomBytes(32).toString('hex');
  patchEnvValue('JWT_SECRET', generated);
  process.env.JWT_SECRET = generated;   // apply to current process too
  console.log('✔  Generated and saved JWT_SECRET to .env (you do not need to do anything).');
}

// ── Ensure ADMIN_PASSWORD is set and strong ──────────────────────────────────
const currentPassword = process.env.ADMIN_PASSWORD ?? '';
if (!currentPassword || currentPassword.length < 8 || KNOWN_WEAK_PASSWORDS.has(currentPassword.toLowerCase())) {
  // Generate a shorter but secure password for readability
  const generated = crypto.randomBytes(12).toString('base64').replace(/[/+=]/g, 'x');
  patchEnvValue('ADMIN_PASSWORD', generated);
  process.env.ADMIN_PASSWORD = generated; // apply to current process too
  console.log(`✔  Generated and saved strong ADMIN_PASSWORD to .env: ${generated}`);
  console.log('   !!! Write this password down! You will need it to login to the admin panel. !!!');
}

// ── Load seller.config.json if present ───────────────────────────────────────
// This file IS committed to git (unlike .env) and is the recommended way for
// non-technical sellers to configure their deployment — no terminal needed.
// env vars always take precedence over the config file.
interface SellerConfig {
  gatewayUrl?: string;
  sellerPublicUrl?: string;
  [key: string]: unknown; // allow _readme / _comment fields
}

let sellerConfig: SellerConfig = {};
const configPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../seller.config.json',   // <repo-root>/seller.config.json
);
if (fs.existsSync(configPath)) {
  try {
    sellerConfig = JSON.parse(fs.readFileSync(configPath, 'utf8')) as SellerConfig;
  } catch (e) {
    console.warn(`⚠  Could not parse seller.config.json: ${e}. Ignoring.`);
  }
}

const DB_PATH = path.join(DATA_DIR, 'catalog.db');

const isReset = process.argv.includes('--reset');

// ── Reset mode: delete registry DB ───────────────────────────────────────────
if (isReset) {
  if (fs.existsSync(DB_PATH)) {
    fs.unlinkSync(DB_PATH);
    console.log(`🗑  Deleted ${DB_PATH}`);
  } else {
    console.log(`ℹ  No DB file found at ${DB_PATH} — will create fresh.`);
  }
}

// ── Ensure directory exists ───────────────────────────────────────────────────
fs.mkdirSync(DATA_DIR, { recursive: true });

// ── Connect & run registry schema ────────────────────────────────────────────
console.log(`📦  Registry DB: ${DB_PATH}`);
const db = new Database(DB_PATH);
initRegistrySchema(db);

// Add profile columns to existing users table if they don't exist
for (const stmt of [
  "ALTER TABLE users ADD COLUMN first_name TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN last_name  TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN email      TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN mobile     TEXT",
  "ALTER TABLE users ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
]) {
  try {
    db.exec(stmt);
  } catch {
    /* column already exists */
  }
}

try {
  db.exec('ALTER TABLE stores ADD COLUMN logo_url TEXT');
} catch { /* column already exists */ }

// Add scoped_role and label columns to user_temp_keys if not yet present
for (const stmt of [
  'ALTER TABLE user_temp_keys ADD COLUMN scoped_role TEXT',
  'ALTER TABLE user_temp_keys ADD COLUMN label       TEXT',
]) {
  try { db.exec(stmt); } catch { /* column already exists */ }
}

try {
  db.exec('ALTER TABLE users ADD COLUMN needs_password_change INTEGER NOT NULL DEFAULT 0');
} catch { /* column already exists */ }

// Add updated_at to other registry tables if missing
for (const stmt of [
  "ALTER TABLE user_stores    ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
  "ALTER TABLE user_temp_keys ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
]) {
  try { db.exec(stmt); } catch { /* already exists */ }
}

// Ensure triggers exist in registry DB
db.exec(`
  CREATE TRIGGER IF NOT EXISTS users_updated_at AFTER UPDATE ON users FOR EACH ROW BEGIN
    UPDATE users SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS settings_updated_at AFTER UPDATE ON settings FOR EACH ROW BEGIN
    UPDATE settings SET updated_at = datetime('now') WHERE key = OLD.key;
  END;
  CREATE TRIGGER IF NOT EXISTS stores_updated_at AFTER UPDATE ON stores FOR EACH ROW BEGIN
    UPDATE stores SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS user_stores_updated_at AFTER UPDATE ON user_stores FOR EACH ROW BEGIN
    UPDATE user_stores SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS user_temp_keys_updated_at AFTER UPDATE ON user_temp_keys FOR EACH ROW BEGIN
    UPDATE user_temp_keys SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
`);

console.log('✔  Registry schema applied (users, settings, stores, user_temp_keys)');

// ── Auto-seed settings from environment variables (non-destructive) ───────────
// These are set once from .env so the admin never has to type them in the UI.
// If a setting already has a value, it is NOT overwritten.
const seedSetting = (key: string, value: string | undefined) => {
  if (!value) return;
  const existing = db
    .prepare('SELECT value FROM settings WHERE key = ?')
    .get(key) as { value: string } | undefined;
  if (!existing) {
    db.prepare('INSERT INTO settings (key, value) VALUES (?, ?)').run(key, value);
    console.log(`✔  Seeded setting "${key}" from environment.`);
  }
};

// env var wins over config file; empty string in config file = "not set"
seedSetting('gateway_url',
  process.env.GATEWAY_URL || sellerConfig.gatewayUrl || undefined,
);
seedSetting('seller_public_url',
  process.env.SELLER_PUBLIC_URL || sellerConfig.sellerPublicUrl || undefined,
);

// ── Seed default admin user ───────────────────────────────────────────────────
const userCount = (db.prepare('SELECT COUNT(*) as n FROM users').get() as { n: number }).n;

if (userCount === 0) {
  const defaultUser = process.env.ADMIN_USERNAME ?? 'admin';
  const defaultPass = process.env.ADMIN_PASSWORD;

  if (!defaultPass || defaultPass === 'admin123' || defaultPass === 'password') {
    throw new Error('CRITICAL: ADMIN_PASSWORD is not set or is set to an insecure default. Please set a strong ADMIN_PASSWORD in your .env file.');
  }

  const hash = bcrypt.hashSync(defaultPass, 10);

  try {
    db.prepare(
      `INSERT INTO users (username, password_hash, role, needs_password_change) VALUES (?, ?, 'super_admin', 1)`
    ).run(defaultUser, hash);

    console.log(`✔  Default admin user created: ${defaultUser}`);
  } catch (error) {
    // Check if another instance already created the admin
    const countAfter = (db.prepare('SELECT COUNT(*) as n FROM users').get() as { n: number }).n;
    if (countAfter === 0) {
      throw error;
    }
    console.log('ℹ  Admin user already exists (likely created by another instance).');
  }
}

db.close();

// ── Migrate all existing per-store DBs ────────────────────────────────────────
// Adds is_synced / deleted_at columns if they don't exist yet.
const storesDir = path.join(DATA_DIR, 'stores');
if (fs.existsSync(storesDir)) {
  const storeFiles = fs.readdirSync(storesDir).filter(f => f.endsWith('.db'));
  for (const file of storeFiles) {
    const storePath = path.join(storesDir, file);
    const sdb = new Database(storePath);
    // Re-apply full schema (CREATE TABLE IF NOT EXISTS is safe)
    initStoreSchema(sdb);
    // Add new columns to existing tables — SQLite doesn't support IF NOT EXISTS
    // for ALTER TABLE, so we catch the "duplicate column" error and continue.
    for (const stmt of [
      'ALTER TABLE products   ADD COLUMN product_type TEXT    NOT NULL DEFAULT \'generic\'',
      'ALTER TABLE products   ADD COLUMN metadata     TEXT    DEFAULT \'{}\'',
      'ALTER TABLE products   ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE products   ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE products   ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE categories ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE categories ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE categories ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE promotions ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE promotions ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE promotions ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE reviews    ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE messages   ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE messages   ADD COLUMN sender_name TEXT',
      'ALTER TABLE conversations ADD COLUMN telegram_chat_id TEXT DEFAULT NULL',
      'ALTER TABLE conversations ADD COLUMN mode TEXT NOT NULL DEFAULT \'ai\'',
      'ALTER TABLE conversations ADD COLUMN assigned_to TEXT',
      'ALTER TABLE conversations ADD COLUMN buyer_name TEXT',
      'ALTER TABLE conversations ADD COLUMN gateway_id INTEGER',
      'ALTER TABLE conversations ADD COLUMN last_message TEXT',
      'ALTER TABLE conversations ADD COLUMN last_message_at TEXT',
      'ALTER TABLE conversations ADD COLUMN message_count INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE orders ADD COLUMN buyer_name TEXT',
      'ALTER TABLE orders ADD COLUMN buyer_email TEXT',
      'ALTER TABLE orders ADD COLUMN delivery_address TEXT',
      'ALTER TABLE orders ADD COLUMN delivery_type TEXT NOT NULL DEFAULT \'delivery\'',
      'ALTER TABLE orders ADD COLUMN tracking_number TEXT',
      'ALTER TABLE orders ADD COLUMN courier_name TEXT',
      'ALTER TABLE orders ADD COLUMN tracking_url TEXT',
      'ALTER TABLE orders ADD COLUMN cancellation_reason TEXT',
      'ALTER TABLE orders ADD COLUMN payment_provider TEXT',
      'ALTER TABLE orders ADD COLUMN payment_instructions TEXT',
      'ALTER TABLE orders ADD COLUMN lat REAL',
      'ALTER TABLE orders ADD COLUMN lng REAL',
      'ALTER TABLE orders ADD COLUMN is_synced INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE orders ADD COLUMN deleted_at TEXT DEFAULT NULL',
      'ALTER TABLE orders ADD COLUMN idempotency_key TEXT DEFAULT NULL',
    ]) {
      try { sdb.exec(stmt); } catch { /* column already exists */ }
    }

    // New tables: product_variants, order_notes and order_files
    sdb.exec(`
      CREATE TABLE IF NOT EXISTS product_variants (
        id             INTEGER PRIMARY KEY AUTOINCREMENT,
        product_id     INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        sku            TEXT    UNIQUE,
        price          REAL    NOT NULL,
        stock          INTEGER NOT NULL DEFAULT 0,
        attributes     TEXT    NOT NULL DEFAULT '{}',
        active         INTEGER NOT NULL DEFAULT 1,
        is_synced      INTEGER NOT NULL DEFAULT 0,
        created_at     TEXT    NOT NULL DEFAULT (datetime('now')),
        updated_at     TEXT    NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS order_notes (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id    INTEGER NOT NULL REFERENCES orders(id),
        note        TEXT NOT NULL,
        created_by  TEXT NOT NULL,
        created_at  TEXT NOT NULL DEFAULT (datetime('now')),
        deleted_at  TEXT DEFAULT NULL,
        deleted_by  TEXT DEFAULT NULL,
        is_synced   INTEGER NOT NULL DEFAULT 0
      );

      CREATE TABLE IF NOT EXISTS order_files (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id      INTEGER NOT NULL REFERENCES orders(id),
        filename      TEXT NOT NULL,
        original_name TEXT NOT NULL,
        file_url      TEXT NOT NULL,
        mime_type     TEXT NOT NULL,
        size_bytes    INTEGER NOT NULL,
        uploaded_by   TEXT NOT NULL,
        uploaded_at   TEXT NOT NULL DEFAULT (datetime('now')),
        deleted_at    TEXT DEFAULT NULL,
        deleted_by    TEXT DEFAULT NULL,
        is_synced     INTEGER NOT NULL DEFAULT 0
      );
    `);

    // Add is_synced trigger for orders
    sdb.exec(`
      CREATE TRIGGER IF NOT EXISTS orders_sync_dirty AFTER UPDATE ON orders FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE orders SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS order_notes_sync_dirty AFTER UPDATE ON order_notes FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1
      BEGIN
        UPDATE order_notes SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS order_files_sync_dirty AFTER UPDATE ON order_files FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1
      BEGIN
        UPDATE order_files SET is_synced = 0 WHERE id = OLD.id;
      END;
    `);

    // Populate denormalized conversation columns if they are empty
    try {
      sdb.exec(`
        UPDATE conversations SET
          last_message = (SELECT body FROM messages WHERE conversation_id = conversations.id ORDER BY created_at DESC LIMIT 1),
          last_message_at = (SELECT created_at FROM messages WHERE conversation_id = conversations.id ORDER BY created_at DESC LIMIT 1),
          message_count = (SELECT COUNT(*) FROM messages WHERE conversation_id = conversations.id)
        WHERE last_message IS NULL AND message_count = 0;
      `);
    } catch (e) {
      console.warn(`⚠ Failed to populate denormalized conversation columns: ${e}`);
    }

    // Add updated_at to order related tables
    for (const stmt of [
      "ALTER TABLE order_notes ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
      "ALTER TABLE order_files ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
      "ALTER TABLE order_items ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
      "ALTER TABLE order_items ADD COLUMN variant_id INTEGER REFERENCES product_variants(id) ON DELETE SET NULL",
    ]) {
      try { sdb.exec(stmt); } catch { /* column already exists */ }
    }

    // Add indexes if missing
    for (const stmt of [
      'CREATE INDEX IF NOT EXISTS idx_conversations_buyer_ref ON conversations(buyer_ref, channel)',
      'CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON conversations(updated_at DESC)',
      'CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations(status)',
      'CREATE INDEX IF NOT EXISTS idx_conversations_gateway_id ON conversations(gateway_id)',
      'CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id)',
      'CREATE INDEX IF NOT EXISTS idx_orders_is_synced ON orders(is_synced)',
      'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)',
      'CREATE INDEX IF NOT EXISTS idx_order_notes_order_id ON order_notes(order_id)',
      'CREATE INDEX IF NOT EXISTS idx_order_files_order_id ON order_files(order_id)',
      'CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON product_variants(product_id)',
      'CREATE INDEX IF NOT EXISTS idx_product_variants_sku ON product_variants(sku)',
      'CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key ON orders(idempotency_key) WHERE idempotency_key IS NOT NULL',
      ]) {

      try { sdb.exec(stmt); } catch { /* index already exists */ }
    }

    // Ensure triggers exist in store DB
    sdb.exec(`
      CREATE TRIGGER IF NOT EXISTS settings_updated_at AFTER UPDATE ON settings FOR EACH ROW BEGIN
        UPDATE settings SET updated_at = datetime('now') WHERE key = OLD.key;
      END;
      CREATE TRIGGER IF NOT EXISTS categories_updated_at AFTER UPDATE ON categories FOR EACH ROW
      WHEN (NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL)
      BEGIN
        UPDATE categories SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS products_updated_at AFTER UPDATE ON products FOR EACH ROW
      WHEN (NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL)
      BEGIN
        UPDATE products SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS promotions_updated_at AFTER UPDATE ON promotions FOR EACH ROW
      WHEN (NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL)
      BEGIN
        UPDATE promotions SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS reviews_updated_at AFTER UPDATE ON reviews FOR EACH ROW
      WHEN (NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL)
      BEGIN
        UPDATE reviews SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS orders_updated_at AFTER UPDATE ON orders FOR EACH ROW BEGIN
        UPDATE orders SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS conversations_updated_at AFTER UPDATE ON conversations FOR EACH ROW BEGIN
        UPDATE conversations SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS messages_updated_at AFTER UPDATE ON messages FOR EACH ROW BEGIN
        UPDATE messages SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS order_notes_updated_at AFTER UPDATE ON order_notes FOR EACH ROW BEGIN
        UPDATE order_notes SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS order_files_updated_at AFTER UPDATE ON order_files FOR EACH ROW BEGIN
        UPDATE order_files SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS order_items_updated_at AFTER UPDATE ON order_items FOR EACH ROW BEGIN
        UPDATE order_items SET updated_at = datetime('now') WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS product_variants_updated_at AFTER UPDATE ON product_variants FOR EACH ROW
      WHEN (NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL)
      BEGIN
        UPDATE product_variants SET updated_at = datetime('now') WHERE id = OLD.id;
      END;

      -- Sync dirty triggers
      CREATE TRIGGER IF NOT EXISTS categories_sync_dirty AFTER UPDATE ON categories FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE categories SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS products_sync_dirty AFTER UPDATE ON products FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE products SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS orders_sync_dirty AFTER UPDATE ON orders FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE orders SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS promotions_sync_dirty AFTER UPDATE ON promotions FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE promotions SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS order_notes_sync_dirty AFTER UPDATE ON order_notes FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE order_notes SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS order_files_sync_dirty AFTER UPDATE ON order_files FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE order_files SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS product_variants_sync_dirty AFTER UPDATE ON product_variants FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1 AND NEW.updated_at = OLD.updated_at
      BEGIN
        UPDATE product_variants SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS product_variants_parent_dirty AFTER UPDATE ON product_variants FOR EACH ROW
      WHEN NEW.is_synced = 0 AND OLD.is_synced = 1
      BEGIN
        UPDATE products SET is_synced = 0 WHERE id = NEW.product_id;
      END;
    `);
    sdb.close();
    console.log(`✔  Migrated store DB: ${file}`);
  }
}

console.log('\n🚀  Migration complete.');
console.log(`   Data directory: ${DATA_DIR}`);
