#!/usr/bin/env tsx
/**
 * Database migration tool for the seller server (SQLite / better-sqlite3).
 *
 * Usage:
 *   npm run db:migrate          — apply schema to registry DB (safe, idempotent)
 *   npm run db:reset            — DROP the registry DB file and recreate from scratch
 *
 * The registry DB (_data/catalog.db) holds: users, settings, stores.
 * Per-store DBs (_data/stores/{slug}.db) are created automatically on first
 * access — no separate migration step needed for them.
 */
import 'dotenv/config'; // ← must be first — loads .env before DATA_DIR is evaluated
import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { initRegistrySchema, initStoreSchema } from './schema.js';
import { DATA_DIR } from './client.js';
import bcrypt from 'bcryptjs';

// ── .env auto-setup ───────────────────────────────────────────────────────────
// Non-technical sellers shouldn't need to touch the .env file.
// If it's missing or has insecure placeholder values we fix it automatically.
const __dir = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.resolve(__dir, '../../../.env');          // prompt-commerce/.env
const EXAMPLE_PATH = path.resolve(__dir, '../../../.env.example');

const KNOWN_WEAK_SECRETS = new Set([
  'change-me-to-a-long-random-string',
  'change-me-in-production',
  'replace_with_generated_secret',
  '',
]);

function ensureEnvFile(): void {
  // Create .env from .env.example if it doesn't exist yet
  if (!fs.existsSync(ENV_PATH)) {
    const template = fs.existsSync(EXAMPLE_PATH)
      ? fs.readFileSync(EXAMPLE_PATH, 'utf8')
      : '# Auto-generated by Prompt Commerce\n';
    fs.writeFileSync(ENV_PATH, template, 'utf8');
    console.log('✔  Created .env from .env.example');
  }
}

function patchEnvValue(key: string, value: string): void {
  ensureEnvFile();
  let content = fs.readFileSync(ENV_PATH, 'utf8');
  const lineRe = new RegExp(`^(#\\s*)?${key}=.*$`, 'm');
  const newLine = `${key}=${value}`;
  if (lineRe.test(content)) {
    content = content.replace(lineRe, newLine);
  } else {
    content += `\n${newLine}\n`;
  }
  fs.writeFileSync(ENV_PATH, content, 'utf8');
}

// ── Ensure JWT_SECRET is set and strong ───────────────────────────────────────
const currentSecret = process.env.JWT_SECRET ?? '';
if (!currentSecret || currentSecret.length < 32 || KNOWN_WEAK_SECRETS.has(currentSecret.toLowerCase())) {
  const generated = crypto.randomBytes(32).toString('hex');
  patchEnvValue('JWT_SECRET', generated);
  process.env.JWT_SECRET = generated;   // apply to current process too
  console.log('✔  Generated and saved JWT_SECRET to .env (you do not need to do anything).');
}

// ── Load seller.config.json if present ───────────────────────────────────────
// This file IS committed to git (unlike .env) and is the recommended way for
// non-technical sellers to configure their deployment — no terminal needed.
// env vars always take precedence over the config file.
interface SellerConfig {
  gatewayUrl?: string;
  sellerPublicUrl?: string;
  [key: string]: unknown; // allow _readme / _comment fields
}

let sellerConfig: SellerConfig = {};
const configPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../seller.config.json',   // <repo-root>/seller.config.json
);
if (fs.existsSync(configPath)) {
  try {
    sellerConfig = JSON.parse(fs.readFileSync(configPath, 'utf8')) as SellerConfig;
  } catch (e) {
    console.warn(`⚠  Could not parse seller.config.json: ${e}. Ignoring.`);
  }
}

const DB_PATH = path.join(DATA_DIR, 'catalog.db');

const isReset = process.argv.includes('--reset');

// ── Reset mode: delete registry DB ───────────────────────────────────────────
if (isReset) {
  if (fs.existsSync(DB_PATH)) {
    fs.unlinkSync(DB_PATH);
    console.log(`🗑  Deleted ${DB_PATH}`);
  } else {
    console.log(`ℹ  No DB file found at ${DB_PATH} — will create fresh.`);
  }
}

// ── Ensure directory exists ───────────────────────────────────────────────────
fs.mkdirSync(DATA_DIR, { recursive: true });

// ── Connect & run registry schema ────────────────────────────────────────────
console.log(`📦  Registry DB: ${DB_PATH}`);
const db = new Database(DB_PATH);
initRegistrySchema(db);

// Add profile columns to existing users table if they don't exist
for (const stmt of [
  "ALTER TABLE users ADD COLUMN first_name TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN last_name  TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN email      TEXT NOT NULL DEFAULT ''",
  "ALTER TABLE users ADD COLUMN mobile     TEXT",
  "ALTER TABLE users ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
]) {
  try {
    db.exec(stmt);
  } catch {
    /* column already exists */
  }
}

// Add scoped_role and label columns to user_temp_keys if not yet present
for (const stmt of [
  'ALTER TABLE user_temp_keys ADD COLUMN scoped_role TEXT',
  'ALTER TABLE user_temp_keys ADD COLUMN label       TEXT',
]) {
  try { db.exec(stmt); } catch { /* column already exists */ }
}

try {
  db.exec('ALTER TABLE users ADD COLUMN needs_password_change INTEGER NOT NULL DEFAULT 0');
} catch { /* column already exists */ }

// Add updated_at to other registry tables if missing
for (const stmt of [
  "ALTER TABLE user_stores    ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
  "ALTER TABLE user_temp_keys ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
]) {
  try { db.exec(stmt); } catch { /* already exists */ }
}

// Ensure triggers exist in registry DB
db.exec(`
  CREATE TRIGGER IF NOT EXISTS users_updated_at AFTER UPDATE ON users FOR EACH ROW BEGIN
    UPDATE users SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS settings_updated_at AFTER UPDATE ON settings FOR EACH ROW BEGIN
    UPDATE settings SET updated_at = datetime('now') WHERE key = OLD.key;
  END;
  CREATE TRIGGER IF NOT EXISTS stores_updated_at AFTER UPDATE ON stores FOR EACH ROW BEGIN
    UPDATE stores SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS user_stores_updated_at AFTER UPDATE ON user_stores FOR EACH ROW BEGIN
    UPDATE user_stores SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
  CREATE TRIGGER IF NOT EXISTS user_temp_keys_updated_at AFTER UPDATE ON user_temp_keys FOR EACH ROW BEGIN
    UPDATE user_temp_keys SET updated_at = datetime('now') WHERE id = OLD.id;
  END;
`);

console.log('✔  Registry schema applied (users, settings, stores, user_temp_keys)');

// ── Auto-seed settings from environment variables (non-destructive) ───────────
// These are set once from .env so the admin never has to type them in the UI.
// If a setting already has a value, it is NOT overwritten.
const seedSetting = (key: string, value: string | undefined) => {
  if (!value) return;
  const existing = db
    .prepare('SELECT value FROM settings WHERE key = ?')
    .get(key) as { value: string } | undefined;
  if (!existing) {
    db.prepare('INSERT INTO settings (key, value) VALUES (?, ?)').run(key, value);
    console.log(`✔  Seeded setting "${key}" from environment.`);
  }
};

// env var wins over config file; empty string in config file = "not set"
seedSetting('gateway_url',
  process.env.GATEWAY_URL || sellerConfig.gatewayUrl || undefined,
);
seedSetting('seller_public_url',
  process.env.SELLER_PUBLIC_URL || sellerConfig.sellerPublicUrl || undefined,
);

// ── Seed default admin user ───────────────────────────────────────────────────
const userCount = (db.prepare('SELECT COUNT(*) as n FROM users').get() as { n: number }).n;

if (userCount === 0) {
  const defaultUser = process.env.ADMIN_USERNAME ?? 'admin';
  const defaultPass = process.env.ADMIN_PASSWORD ?? 'admin123';
  const hash = bcrypt.hashSync(defaultPass, 10);

  db.prepare(
    `INSERT INTO users (username, password_hash, role, needs_password_change) VALUES (?, ?, 'admin', 1)`
  ).run(defaultUser, hash);

  console.log(`✔  Default admin user created: ${defaultUser} / ${defaultPass}`);
  console.log('   ⚠  Change this password in Settings before going live!');
}

db.close();

// ── Migrate all existing per-store DBs ────────────────────────────────────────
// Adds is_synced / deleted_at columns if they don't exist yet.
const storesDir = path.join(DATA_DIR, 'stores');
if (fs.existsSync(storesDir)) {
  const storeFiles = fs.readdirSync(storesDir).filter(f => f.endsWith('.db'));
  for (const file of storeFiles) {
    const storePath = path.join(storesDir, file);
    const sdb = new Database(storePath);
    // Re-apply full schema (CREATE TABLE IF NOT EXISTS is safe)
    initStoreSchema(sdb);
    // Add new columns to existing tables — SQLite doesn't support IF NOT EXISTS
    // for ALTER TABLE, so we catch the "duplicate column" error and continue.
    for (const stmt of [
      'ALTER TABLE products   ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE products   ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE products   ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE categories ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE categories ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE categories ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE promotions ADD COLUMN is_synced  INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE promotions ADD COLUMN deleted_at TEXT    DEFAULT NULL',
      'ALTER TABLE promotions ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE reviews    ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
      'ALTER TABLE messages   ADD COLUMN updated_at TEXT    NOT NULL DEFAULT (datetime(\'now\'))',
    ]) {
      try { sdb.exec(stmt); } catch { /* column already exists */ }
    }

    // Ensure triggers exist in store DB
    sdb.exec(`
      CREATE TRIGGER IF NOT EXISTS settings_updated_at AFTER UPDATE ON settings FOR EACH ROW BEGIN
        UPDATE settings SET updated_at = datetime('now') WHERE key = OLD.key;
      END;
      CREATE TRIGGER IF NOT EXISTS categories_updated_at AFTER UPDATE ON categories FOR EACH ROW BEGIN
        UPDATE categories SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS products_updated_at AFTER UPDATE ON products FOR EACH ROW BEGIN
        UPDATE products SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS promotions_updated_at AFTER UPDATE ON promotions FOR EACH ROW BEGIN
        UPDATE promotions SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS reviews_updated_at AFTER UPDATE ON reviews FOR EACH ROW BEGIN
        UPDATE reviews SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS orders_updated_at AFTER UPDATE ON orders FOR EACH ROW BEGIN
        UPDATE orders SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS conversations_updated_at AFTER UPDATE ON conversations FOR EACH ROW BEGIN
        UPDATE conversations SET updated_at = datetime('now') WHERE id = OLD.id;
      END;
      CREATE TRIGGER IF NOT EXISTS messages_updated_at AFTER UPDATE ON messages FOR EACH ROW BEGIN
        UPDATE messages SET updated_at = datetime('now') WHERE id = OLD.id;
      END;

      -- Sync dirty triggers
      CREATE TRIGGER IF NOT EXISTS categories_sync_dirty AFTER UPDATE ON categories FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1
      BEGIN
        UPDATE categories SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS products_sync_dirty AFTER UPDATE ON products FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1
      BEGIN
        UPDATE products SET is_synced = 0 WHERE id = OLD.id;
      END;

      CREATE TRIGGER IF NOT EXISTS promotions_sync_dirty AFTER UPDATE ON promotions FOR EACH ROW
      WHEN NEW.is_synced = OLD.is_synced AND NEW.is_synced = 1
      BEGIN
        UPDATE promotions SET is_synced = 0 WHERE id = OLD.id;
      END;
    `);
    sdb.close();
    console.log(`✔  Migrated store DB: ${file}`);
  }
}

console.log('\n🚀  Migration complete.');
console.log(`   Data directory: ${DATA_DIR}`);
